export const mockNotifications = [
  {
    id: 1,
    title: "Received from Anna",
    amount: +110,
    category: "Payments",
    icon: "/assets/notifications/avatar.png",
    cardName: "Debit",
    cardLast4: "4385",
    balanceAfter: 4098.12,
    date: "17 June 2025",
    time: "17:49",
    type: "Payments",
  },
  {
    id: 2,
    title: "See our limited offer!",
    amount: null,
    category: "Travel",
    icon: "/assets/notifications/planet.png",
    type: "Travel",
    date: "16 June 2025",
    time: "23:08",
    cardName: "Would you like to visit new countries? Maybe it’s your time!",
    cardLast4: null,
    balanceAfter: null,
  },
  {
    id: 3,
    title: "Sent to •• 2041",
    amount: -14.62,
    category: "Payments",
    icon: "/assets/notifications/arrow.png",
    type: "Payments",
    date: "16 June 2025",
    time: "06:18",

    cardName: "Debit",
    cardLast4: 4385,
    balanceAfter: 3987.5,
  },
  {
    id: 4,
    title: "New login into account",
    amount: null,
    category: "Security",
    icon: "/assets/notifications/shield.png",
    type: "Security",
    date: "24 March 2025",
    time: "15:44",

    cardName: "You have logged in from a new location: iOS 26.0.1 · 109.255.84.7 · Spain",
    cardLast4: null,
    balanceAfter: null,
  },
];
